spring.application.name=media


spring.datasource.url=jdbc:postgresql://localhost:5433/media_db
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082